/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesBusinessFormationRouteImport } from './routes/services.business-formation'
import { Route as ServicesPaymentPlatformsRouteImport } from './routes/services.payment-platforms'
import { Route as ServicesPaymentPlatformsPlatformRouteImport } from './routes/services.payment-platforms.$platform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBusinessFormationRoute =
  ServicesBusinessFormationRouteImport.update({
    id: '/business-formation',
    path: '/business-formation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPaymentPlatformsRoute =
  ServicesPaymentPlatformsRouteImport.update({
    id: '/payment-platforms',
    path: '/payment-platforms',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPaymentPlatformsPlatformRoute =
  ServicesPaymentPlatformsPlatformRouteImport.update({
    id: '/$platform',
    path: '/$platform',
    getParentRoute: () => ServicesPaymentPlatformsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/payment-platforms': typeof ServicesPaymentPlatformsRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/payment-platforms/$platform': typeof ServicesPaymentPlatformsPlatformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/payment-platforms': typeof ServicesPaymentPlatformsRouteWithChildren
  '/services': typeof ServicesIndexRoute
  '/services/payment-platforms/$platform': typeof ServicesPaymentPlatformsPlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/payment-platforms': typeof ServicesPaymentPlatformsRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/payment-platforms/$platform': typeof ServicesPaymentPlatformsPlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/resources'
    | '/services'
    | '/solutions'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/services/business-formation'
    | '/services/payment-platforms'
    | '/services/'
    | '/services/payment-platforms/$platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/resources'
    | '/solutions'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/services/business-formation'
    | '/services/payment-platforms'
    | '/services'
    | '/services/payment-platforms/$platform'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/resources'
    | '/services'
    | '/solutions'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/services/business-formation'
    | '/services/payment-platforms'
    | '/services/'
    | '/services/payment-platforms/$platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/business-formation': {
      id: '/services/business-formation'
      path: '/business-formation'
      fullPath: '/services/business-formation'
      preLoaderRoute: typeof ServicesBusinessFormationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/payment-platforms': {
      id: '/services/payment-platforms'
      path: '/payment-platforms'
      fullPath: '/services/payment-platforms'
      preLoaderRoute: typeof ServicesPaymentPlatformsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/payment-platforms/$platform': {
      id: '/services/payment-platforms/$platform'
      path: '/$platform'
      fullPath: '/services/payment-platforms/$platform'
      preLoaderRoute: typeof ServicesPaymentPlatformsPlatformRouteImport
      parentRoute: typeof ServicesPaymentPlatformsRoute
    }
  }
}

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface ServicesPaymentPlatformsRouteChildren {
  ServicesPaymentPlatformsPlatformRoute: typeof ServicesPaymentPlatformsPlatformRoute
}

const ServicesPaymentPlatformsRouteChildren: ServicesPaymentPlatformsRouteChildren =
  {
    ServicesPaymentPlatformsPlatformRoute:
      ServicesPaymentPlatformsPlatformRoute,
  }

const ServicesPaymentPlatformsRouteWithChildren =
  ServicesPaymentPlatformsRoute._addFileChildren(
    ServicesPaymentPlatformsRouteChildren,
  )

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesBusinessFormationRoute: typeof ServicesBusinessFormationRoute
  ServicesPaymentPlatformsRoute: typeof ServicesPaymentPlatformsRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesBusinessFormationRoute: ServicesBusinessFormationRoute,
  ServicesPaymentPlatformsRoute: ServicesPaymentPlatformsRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
